In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../Dataset/clustered_df.csv')
df.head()

,customer_id,customer_unique_id,customers_zip_code_prefix,customer_city,customer_state,customers_geolocation_lat,customers_geolocation_lng,order_id,order_status,order_purchase_timestamp,...,sellers_zip_code_prefix,seller_city,seller_state,sellers_geolocation_lat,sellers_geolocation_lng,Length,Recency,Frequency,Monetary,Cluster
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,-20.509898,-47.397866,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,...,8577.0,itaquaquecetuba,SP,-23.482623,-46.374490,519.0,519.0,1.0,146.87,1.0
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,-23.726853,-46.545746,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,...,88303.0,itajai,SC,-26.912429,-48.677381,277.0,277.0,1.0,335.48,0.0
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,-23.527788,-46.660310,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,...,8577.0,itaquaquecetuba,SP,-23.482623,-46.374490,151.0,151.0,1.0,157.73,0.0
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,-23.496930,-46.185352,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,...,8577.0,itaquaquecetuba,SP,-23.482623,-46.374490,218.0,218.0,1.0,173.30,0.0
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,-22.987222,-47.151073,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,...,14940.0,ibitinga,SP,-21.766477,-48.831547,80.0,80.0,1.0,252.25,0.0

1. Filter by State: Write a query to filter the dataset for customers from the state "SP". Display only the columns customer_id, customer_city, and customer_state.

In [12]:
df[['customer_id','customer_city','customer_state']].loc[df['customer_state'] == 'SP'].head()

                        customer_id          customer_city customer_state
0  06b8999e2fba1a1fbc88172c00ba8bc7                 franca             SP
1  18955e83d337fd6b2def6b18a428ac77  sao bernardo do campo             SP
2  4e7b3e00288586ebd08712fdd0374a03              sao paulo             SP
3  b2b6027bc5c5109e529d4dc6358b12c3        mogi das cruzes             SP
4  4f2d8ab171c80ec8364f7c12e35b23ad               campinas             SP

2. Filter by Order Status: Create a filter to display all orders that have a status of "delivered". Show the order_id, customer_id, order_status, and order_purchase_timestamp.

In [14]:
df[['order_id','customer_id','order_status','order_purchase_timestamp']].loc[df['order_status'] == 'delivered']

,order_id,customer_id,order_status,order_purchase_timestamp
0,00e7ee1b050b8499577073aeb2a297a1,06b8999e2fba1a1fbc88172c00ba8bc7,delivered,2017-05-16 15:05:35
1,29150127e6685892b6eab3eec79f59c7,18955e83d337fd6b2def6b18a428ac77,delivered,2018-01-12 20:48:24
2,b2059ed67ce144a36e2aa97d2c9e9ad2,4e7b3e00288586ebd08712fdd0374a03,delivered,2018-05-19 16:07:45
3,951670f92359f4fe4a63112aa7306eba,b2b6027bc5c5109e529d4dc6358b12c3,delivered,2018-03-13 16:06:38
4,6b7d50bd145f6fc7f33cebabd7e49d0f,4f2d8ab171c80ec8364f7c12e35b23ad,delivered,2018-07-29 09:51:30
...,...,...,...,...
119138,6760e20addcf0121e9d58f2f1ff14298,17ddf5dd5d51696bb3d7c6291687be6f,delivered,2018-04-07 15:48:17
119139,9ec0c8947d973db4f4e8dcf1fbfa8f1b,e7b71a9017aa05c9a7fd292d714858e8,delivered,2018-04-04 08:20:22
119140,fed4434add09a6f332ea398efd656a5c,5e28dfe12db7fb50a4b2f691faecea5e,delivered,2018-04-08 20:11:50
119141,e31ec91cea1ecf97797787471f98a8c2,56b18e2166679b8a959d72dd06da27f9,delivered,2017-11-03 21:08:33
119142,28db69209a75e59f20ccbb5c36a20b90,274fa6071e5e17fe303b9748641082c8,delivered,2017-12-19 14:27:23

3. Filter by Purchase Date Range: Write a query to filter orders that were purchased between "2018-01-01" and "2018-12-31". Display the order_id, order_purchase_timestamp, and order_status.

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 46 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   customer_id                    119143 non-null  object
 1   customer_unique_id             119143 non-null  object
 2   customers_zip_code_prefix      119143 non-null  int64
 3   customer_city                  119143 non-null  object
 4   customer_state                 119143 non-null  object
 5   customers_geolocation_lat      118821 non-null  float64
 6   customers_geolocation_lng      118821 non-null  float64
 7   order_id                       119143 non-null  object
 8   order_status                   119143 non-null  object
 9   order_purchase_timestamp       119143 non-null  datetime64[ns]
 10  order_approved_at              118966 non-null  object
 11  order_delivered_carrier_date   117057 non-null  object
 12  order_delivered_customer_date  115722 non-null  object
 13  order_estimated_delivery_date  119143 non-null  object
 14  is_late_shipped                119143 non-null  int64
 15  is_late_delivered              119143 non-null  int64
 16  order_item_id                  118310 non-null  float64
 17  product_id                     118310 non-null  object
 18  seller_id                      118310 non-null  object
 19  shipping_limit_date            118310 non-null  object
 20  price                          118310 non-null  float64
 21  freight_value                  118310 non-null  float64
 22  payment_sequential             119137 non-null  float64
 23  payment_type                   119137 non-null  object
 24  payment_installments           119137 non-null  float64
 25  payment_value                  119137 non-null  float64
 26  review_score                   118146 non-null  float64
 27  review_creation_date           118146 non-null  object
 28  review_answer_timestamp        118146 non-null  object
 29  days_review_answered           118146 non-null  float64
 30  product_name_lenght            118310 non-null  float64
 31  product_description_lenght     118310 non-null  float64
 32  product_photos_qty             118310 non-null  float64
 33  product_weight_g               118310 non-null  float64
 34  product_volume_cm3             118310 non-null  float64
 35  product_category_name          118310 non-null  object
 36  sellers_zip_code_prefix        118310 non-null  float64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
 39  sellers_geolocation_lat        118045 non-null  float64
 40  sellers_geolocation_lng        118045 non-null  float64
 41  Length                         119138 non-null  float64
 42  Recency                        119138 non-null  float64
 43  Frequency                      119138 non-null  float64
 44  Monetary                       119138 non-null  float64
 45  Cluster                        119138 non-null  float64
dtypes: datetime64[ns](1), float64(23), int64(3), object(19)
memory usage: 41.8+ MB

In [3]:
import pandas as pd
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

In [23]:
df[['order_id','order_purchase_timestamp','order_status']].loc[(df['order_purchase_timestamp'] > '2018-01-01') & (df['order_purchase_timestamp'] < '2018-12-31')]

                                order_id order_purchase_timestamp order_status
1       29150127e6685892b6eab3eec79f59c7      2018-01-12 20:48:24    delivered
2       b2059ed67ce144a36e2aa97d2c9e9ad2      2018-05-19 16:07:45    delivered
3       951670f92359f4fe4a63112aa7306eba      2018-03-13 16:06:38    delivered
4       6b7d50bd145f6fc7f33cebabd7e49d0f      2018-07-29 09:51:30    delivered
6       36e694cf4cbc2a4803200c35e84abdc4      2018-02-19 14:38:35    delivered
...                                  ...                      ...          ...
119133  ca978d2459ea2c5ef6d5fde02be26b9c      2018-03-06 09:16:56    delivered
119136  97d6c1727b0d36b8d04035e35d86f40f      2018-05-18 21:42:33    delivered
119138  6760e20addcf0121e9d58f2f1ff14298      2018-04-07 15:48:17    delivered
119139  9ec0c8947d973db4f4e8dcf1fbfa8f1b      2018-04-04 08:20:22    delivered
119140  fed4434add09a6f332ea398efd656a5c      2018-04-08 20:11:50    delivered

[64185 rows x 3 columns]

4. Slice Top N Records: Write a query to display the top 10 records from the dataset to get a quick overview of the first few entries.

In [24]:
df.head(10)

,customer_id,customer_unique_id,customers_zip_code_prefix,customer_city,customer_state,customers_geolocation_lat,customers_geolocation_lng,order_id,order_status,order_purchase_timestamp,...,sellers_zip_code_prefix,seller_city,seller_state,sellers_geolocation_lat,sellers_geolocation_lng,Length,Recency,Frequency,Monetary,Cluster
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,-20.509898,-47.397866,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,...,8577.0,itaquaquecetuba,SP,-23.482623,-46.374490,519.0,519.0,1.0,146.87,1.0
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,-23.726853,-46.545746,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,...,88303.0,itajai,SC,-26.912429,-48.677381,277.0,277.0,1.0,335.48,0.0
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,-23.527788,-46.660310,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,...,8577.0,itaquaquecetuba,SP,-23.482623,-46.374490,151.0,151.0,1.0,157.73,0.0
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,-23.496930,-46.185352,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,...,8577.0,itaquaquecetuba,SP,-23.482623,-46.374490,218.0,218.0,1.0,173.30,0.0
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,-22.987222,-47.151073,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,...,14940.0,ibitinga,SP,-21.766477,-48.831547,80.0,80.0,1.0,252.25,0.0
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC,-26.468503,-49.109883,5741ea1f91b5fbab2bd2dc653a5b5099,delivered,2017-09-14 18:14:31,...,5141.0,piratuba,SP,-23.490660,-46.728476,397.0,367.0,2.0,565.88,3.0
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP,-23.584547,-46.674561,36e694cf4cbc2a4803200c35e84abdc4,delivered,2018-02-19 14:38:35,...,4102.0,sao paulo,SP,-23.592724,-46.631584,240.0,240.0,1.0,22.77,0.0
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG,-19.579882,-42.645924,1093c8304c7a003280dd34598194913d,delivered,2017-11-16 19:29:02,...,4142.0,sao paulo,SP,-23.611654,-46.632588,334.0,334.0,1.0,36.01,1.0
8,5adf08e34b2e993982a47070956c5c65,1175e95fb47ddff9de6b2b06188f7e0d,81560,curitiba,PR,-25.496853,-49.209023,1ebeea841c590e86a14a0d7a48e7d062,delivered,2018-01-18 12:35:44,...,21210.0,rio de janeiro,RJ,-22.842290,-43.297621,272.0,272.0,2.0,83.19,0.0
9,4b7139f34592b3a31687243a302fa75b,9afe194fb833f79e300e37e580171f22,30575,belo horizonte,MG,-19.970076,-43.979595,7433cbcc783205509d66a5260da5b574,delivered,2018-01-08 11:22:34,...,80330.0,curitiba,PR,-25.472735,-49.305638,282.0,282.0,1.0,122.47,0.0

5. Filter by Monetary Value: Create a filter to display customers whose Monetary value is greater than 200. Show the customer_id, Monetary, and Cluster columns.

In [25]:
df[['customer_id','Monetary','Cluster']].loc[df['Monetary'] > 200]

                             customer_id  Monetary  Cluster
1       18955e83d337fd6b2def6b18a428ac77    335.48      0.0
4       4f2d8ab171c80ec8364f7c12e35b23ad    252.25      0.0
5       879864dab9bc3047522c92c82e1212b8    565.88      3.0
13      eabebad39a88bb6f5b52376faec28612    281.50      0.0
22      690172ab319622688d3b4df42f676898    232.71      1.0
...                                  ...       ...      ...
119109  b7c889215de76857c7967c1011125d2d    662.34      3.0
119110  b7c889215de76857c7967c1011125d2d    662.34      3.0
119111  b7c889215de76857c7967c1011125d2d    662.34      3.0
119112  b7c889215de76857c7967c1011125d2d    662.34      3.0
119141  56b18e2166679b8a959d72dd06da27f9    711.07      3.0

[32003 rows x 3 columns]

6. Slicing Specific Columns: Write a query to select and display only the columns related to geolocation: customers_geolocation_lat, customers_geolocation_lng, sellers_geolocation_lat, sellers_geolocation_lng.

In [27]:
geolocation = df[['customers_geolocation_lat','customers_geolocation_lng','sellers_geolocation_lat','sellers_geolocation_lng']]
geolocation

,customers_geolocation_lat,customers_geolocation_lng,sellers_geolocation_lat,sellers_geolocation_lng
0,-20.509898,-47.397866,-23.482623,-46.374490
1,-23.726853,-46.545746,-26.912429,-48.677381
2,-23.527788,-46.660310,-23.482623,-46.374490
3,-23.496930,-46.185352,-23.482623,-46.374490
4,-22.987222,-47.151073,-21.766477,-48.831547
...,...,...,...,...
119138,-23.587901,-46.501830,-22.218989,-49.643623
119139,-23.612294,-46.765787,-21.760806,-48.172285
119140,-3.744128,-38.510859,-23.544897,-46.577772
119141,-29.956391,-51.167614,-21.362358,-48.232976
119142,-23.593985,-46.910591,-23.502716,-46.482996

7. Filter by Frequency and Recency: Write a filter to display customers with a Frequency of 1 and a Recency less than 100. Display customer_id, Frequency, and Recency.

In [28]:
df[['customer_id','Frequency','Recency']].loc[(df['Frequency'] == 1) & (df['Recency'] < 100)]

                             customer_id  Frequency  Recency
4       4f2d8ab171c80ec8364f7c12e35b23ad        1.0     80.0
16      a7c125a0a07b75146167b7f04a7f8e98        1.0     64.0
29      167bd30a409e3e4127df5a9408ebd394        1.0     95.0
83      7300450cedf7e4c35c243c4a03c1e8a6        1.0     78.0
92      6c9a5923526346cbc0bd7bbd92269c01        1.0     56.0
...                                  ...        ...      ...
119091  cf1ec2659f4b1f34f858a0c25e1d5d1a        1.0     74.0
119092  4951ae40c746cbd07eecef33fc053e89        1.0     81.0
119098  f6c6d3e1e20969a5eed982163f959719        1.0     95.0
119099  330786b82d1da4f900da3f8124a9f4f0        1.0     90.0
119106  c156d63bdfce1d456bd43cf1c4dadfca        1.0     88.0

[12537 rows x 3 columns]

8. Filter by Cluster Group: Filter and display all entries where the Cluster is 0. Display the customer_id, Monetary, and Cluster.

In [29]:
df[['customer_id','Monetary','Cluster']].loc[df['Cluster'] == 0]

                             customer_id  Monetary  Cluster
1       18955e83d337fd6b2def6b18a428ac77    335.48      0.0
2       4e7b3e00288586ebd08712fdd0374a03    157.73      0.0
3       b2b6027bc5c5109e529d4dc6358b12c3    173.30      0.0
4       4f2d8ab171c80ec8364f7c12e35b23ad    252.25      0.0
6       fd826e7cf63160e536e0908c76c3f441     22.77      0.0
...                                  ...       ...      ...
119137  7fe2e80252a9ea476f950ae8f85b0f8f     75.88      0.0
119138  17ddf5dd5d51696bb3d7c6291687be6f     88.78      0.0
119139  e7b71a9017aa05c9a7fd292d714858e8    129.06      0.0
119140  5e28dfe12db7fb50a4b2f691faecea5e     56.04      0.0
119142  274fa6071e5e17fe303b9748641082c8     21.77      0.0

[59715 rows x 3 columns]

9. Filter and Sort by Monetary Value: Write a query to filter orders where order_status is "delivered" and sort the result by Monetary in descending order. Display order_id, Monetary, and order_status.

In [31]:
df[['order_id','Monetary','order_status']].loc[df['order_status'] == 'delivered']

                                order_id  Monetary order_status
0       00e7ee1b050b8499577073aeb2a297a1    146.87    delivered
1       29150127e6685892b6eab3eec79f59c7    335.48    delivered
2       b2059ed67ce144a36e2aa97d2c9e9ad2    157.73    delivered
3       951670f92359f4fe4a63112aa7306eba    173.30    delivered
4       6b7d50bd145f6fc7f33cebabd7e49d0f    252.25    delivered
...                                  ...       ...          ...
119138  6760e20addcf0121e9d58f2f1ff14298     88.78    delivered
119139  9ec0c8947d973db4f4e8dcf1fbfa8f1b    129.06    delivered
119140  fed4434add09a6f332ea398efd656a5c     56.04    delivered
119141  e31ec91cea1ecf97797787471f98a8c2    711.07    delivered
119142  28db69209a75e59f20ccbb5c36a20b90     21.77    delivered

[115723 rows x 3 columns]

10. Multiple Filters: Write a query to filter customers who are from the state "SP" and have a Monetary value above 100. Display customer_id, customer_city, customer_state, and Monetary.

In [33]:
df[['customer_id','customer_city','customer_state','Monetary']].loc[(df['customer_state']=='SP') & (df['Monetary']>100)]

,customer_id,customer_city,customer_state,Monetary
0,06b8999e2fba1a1fbc88172c00ba8bc7,franca,SP,146.87
1,18955e83d337fd6b2def6b18a428ac77,sao bernardo do campo,SP,335.48
2,4e7b3e00288586ebd08712fdd0374a03,sao paulo,SP,157.73
3,b2b6027bc5c5109e529d4dc6358b12c3,mogi das cruzes,SP,173.30
4,4f2d8ab171c80ec8364f7c12e35b23ad,campinas,SP,252.25
...,...,...,...,...
119128,ffa6d90c36a9c7004692ca50761c69d6,paulinia,SP,130.85
119131,27b9b32173455ef32167540451749d0b,cotia,SP,102.03
119133,f255d679c7c86c24ef4861320d5b7675,rio claro,SP,108.59
119136,f5a0b560f9e9427792a88bec97710212,cajamar,SP,132.64
119139,e7b71a9017aa05c9a7fd292d714858e8,taboao da serra,SP,129.06

11. Count Unique Values: Write a query to find the number of unique customer_unique_id values in the dataset. This will help to understand the count of unique customers.

In [34]:
df['customer_unique_id'].value_counts()

customer_unique_id
9a736b248f67d166d2fbb006bcb877c3    75
6fbc7cdadbb522125f4b27ae9dee4060    38
f9ae226291893fda10af7965268fb7f6    35
8af7ac63b2efbcbd88e5b11505e8098a    29
569aa12b73b5f7edeaa6f2a01603e381    26
                                    ..
5e809f39163aadeda694b51606b02d49     1
368ad1cd5eb8e06bb9b4cae407bb4bf2     1
302c1a15f1ada723f22801b30293cde3     1
2880d08cd241936c6ce9a1f916ed30fe     1
84732c5050c01db9b23e19ba39899398     1
Name: count, Length: 96096, dtype: int64

12. Calculate Average Monetary Value: Write a query to calculate the average Monetary value for each customer cluster. Display the Cluster and the calculated average Monetary value.

In [54]:
df[['Cluster','Monetary']].groupby(by='Cluster').agg({
'Monetary' : ['mean']
})

            Monetary
                mean
Cluster
0.0       124.906285
1.0       125.862763
2.0      1940.190682
3.0       573.248897

13. Find Top N Customers by Monetary Value: Write a query to find the top 5 customers with the highest Monetary value. Display customer_id and Monetary.

In [77]:
customer_monetary = df.groupby('customer_id')['Monetary'].sum().reset_index()
customer_monetary.sort_values('Monetary',ascending=False).head(5)

                            customer_id   Monetary
8546   1617b1357756262bfa56ab541c47bc16  109312.64
73858  bd5d39761aa56689a265d95d8d32b8be   45256.00
74118  be1b70680b9f9694d8c70f41fa3dc92b   44048.00
2065   05455dfa7cd02f13d132aa7a6a9729c6   36489.24
54314  8c20d9bfbc96c5d39025d77a3ba83d7f   30613.11

14. Group and Aggregate by City: Write a query to group the dataset by customer_city and count the number of customers in each city. Display customer_city and the count of customers.

In [71]:
city = df.groupby('customer_city')['customer_id'].nunique().reset_index()
city.columns = ['customer_city','customer_count']
city.sort_values('customer_count',ascending=False)

       customer_city  customer_count
3442       sao paulo           15540
3021  rio de janeiro            6882
428   belo horizonte            2773
529         brasilia            2131
1090        curitiba            1521
...              ...             ...
2092       mampituba               1
2091         mamonas               1
2086        malhador               1
2083   major isidoro               1
1967      lagoa real               1

[3934 rows x 2 columns]

15. Filter by Geographic Coordinates: Write a query to filter customers located within a specific range of latitude and longitude. For example, find customers located between latitude -24 and -22 and longitude -47 and -45. Display customer_id, customers_geolocation_lat, and customers_geolocation_lng.

In [79]:
df[['customer_id','customers_geolocation_lat','customers_geolocation_lng']].loc[((df['customers_geolocation_lat'] >= -24) & (df['customers_geolocation_lat'] <= -22)) & ((df['customers_geolocation_lng'] >= -47) & (df['customers_geolocation_lng'] <= -45)) ]

,customer_id,customers_geolocation_lat,customers_geolocation_lng
1,18955e83d337fd6b2def6b18a428ac77,-23.726853,-46.545746
2,4e7b3e00288586ebd08712fdd0374a03,-23.527788,-46.660310
3,b2b6027bc5c5109e529d4dc6358b12c3,-23.496930,-46.185352
6,fd826e7cf63160e536e0908c76c3f441,-23.584547,-46.674561
13,eabebad39a88bb6f5b52376faec28612,-23.628827,-46.719233
...,...,...,...
119130,1ed0c832c2dd99570a59260e71768bdf,-22.469555,-46.147500
119136,f5a0b560f9e9427792a88bec97710212,-23.406238,-46.841025
119138,17ddf5dd5d51696bb3d7c6291687be6f,-23.587901,-46.501830
119139,e7b71a9017aa05c9a7fd292d714858e8,-23.612294,-46.765787
119142,274fa6071e5e17fe303b9748641082c8,-23.593985,-46.910591

16. Pivot Table for Order Status: Create a pivot table to summarize the count of orders (order_id) by order_status for each customer_state. Display customer_state as the rows, order_status as the columns, and the count of orders as the values.

In [85]:
# Create a pivot table to summarize the count of orders by order_status for each customer_state
pivot_table = df.pivot_table(
    index='customer_state',  # Rows
    columns='order_status',  # Columns
    values='order_id',       # Values
    aggfunc='count',
    fill_value=0   
)

# Display the pivot table
pivot_table

order_status,approved,canceled,created,delivered,invoiced,processing,shipped,unavailable
customer_state,,,,,,,,
AC,0,0,0,94,0,0,1,0
AL,0,1,0,445,2,6,9,1
AM,0,0,0,170,0,0,2,1
AP,0,0,0,83,0,1,0,0
BA,0,17,0,3950,9,16,78,21
CE,0,7,0,1504,1,6,41,6
DF,0,11,1,2447,3,8,33,13
ES,0,12,0,2318,4,2,17,7
GO,0,15,0,2395,5,7,35,9
MA,0,4,0,823,2,0,20,7
MG,2,75,0,13496,46,35,79,86
MS,0,2,0,848,1,3,3,5
MT,0,2,0,1082,1,1,43,3
PA,0,4,0,1097,2,3,20,3
PB,0,3,0,624,1,2,11,3
PE,0,5,0,1840,5,10,41,5
PI,0,5,0,554,4,3,9,1
PR,0,29,1,5894,17,17,37,48
RJ,0,96,1,14963,28,34,325,71
RN,0,0,0,563,0,1,7,3
RO,0,3,0,281,1,3,0,4
RR,0,1,0,46,0,0,5,0
RS,0,33,1,6431,29,14,40,25
SC,0,21,0,4239,17,16,33,19
SE,0,1,0,386,1,0,10,5
SP,1,402,1,48816,199,187,354,305
TO,0,1,0,334,0,1,3,1

17. Group by Cluster and Aggregate: Write a query to group the dataset by Cluster and calculate the total Monetary value and the average Recency for each cluster. Display Cluster, total Monetary, and average Recency.

In [93]:
cluster = df.groupby('Cluster').agg({
    'Monetary':['sum'],
    'Recency':['mean']
}).reset_index()
cluster.columns = ['Cluster','Monetary Total','Average Recency']
cluster

   Cluster  Monetary Total  Average Recency
0      0.0      7458778.81       177.272277
1      1.0      5755955.88       436.198242
2      2.0      3015056.32       280.572716
3      3.0      6957521.86       278.715910

18. Group by Customer City: Write a query to group the dataset by customer_city and calculate the total number of orders (order_id) and the average Monetary value for each city. Display customer_city, total orders, and average Monetary.

In [4]:
df.groupby('customer_city').agg(
    total_order = ('order_id','nunique'),
    average_monetary = ('Monetary','mean')
).reset_index()

            customer_city  total_order  average_monetary
0         abadia de goias            1         34.090000
1     abadia dos dourados            4        124.207500
2               abadiania            1       1025.520000
3                  abaete           12        162.234167
4              abaetetuba           11        420.314667
...                   ...          ...               ...
3929             xinguara            9        172.663000
3930          xique-xique            3         76.853333
3931             zacarias            2        114.925000
3932              ze doca            5        175.784000
3933               zortea            2         68.785000

[3934 rows x 3 columns]

19. Multi-Level Grouping: Perform a multi-level grouping by customer_state and order_status to calculate the average Monetary value. Display customer_state, order_status, and average Monetary.

In [5]:
df.groupby(['customer_state','order_status'])['Monetary'].mean().reset_index()

    customer_state order_status    Monetary
0               AC    delivered  302.540106
1               AC      shipped   94.370000
2               AL     canceled  639.980000
3               AL    delivered  267.009573
4               AL     invoiced   86.055000
..             ...          ...         ...
144             TO     canceled  250.570000
145             TO    delivered  247.518353
146             TO   processing   96.980000
147             TO      shipped  333.166667
148             TO  unavailable  130.910000

[149 rows x 3 columns]

20. Pivot Table with Aggregation: Create a pivot table that shows the average Monetary value for each combination of customer_state and order_status. Use customer_state as rows and order_status as columns, with the average Monetary value as the pivot table's values.

TypeError: 'str' object is not callable